# Generated by Django 5.1.5 on 2025-01-30 11:28

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.CharField(default='defaultusername', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
